version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - ecologistik-net

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - ecologistik-net
    depends_on:
      - backend

networks:
  ecologistik-net:
